spring:
  datasource:
    username: root
    password: password
    url: jdbc:mysql://localhost:3306/ry?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver